build: run spotless manually

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -100,3 +100,31 @@ jobs:
             EXTRA_FLAGS="-X"
           fi
             mvn -B $EXTRA_FLAGS verify --file pom.xml
+  lint:
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    strategy:
+      fail-fast: false
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v5
+        with:
+          # Needed for spotless to do the ratchet
+          fetch-depth: 0
+          show-progress: false
+      - name: Run OpenRewrite
+        run: |
+          mvn rewrite:run --file pom.xml
+          if [ -z "$(git status --porcelain)" ]; then 
+            echo "rewrite PASS"
+          else 
+            echo "rewrite FAIL; run `mvn rewrite:run` locally" >&2
+          fi
+      - name: Run spotless
+        run: |
+          mvn spotless:apply --file pom.xml
+          if [ -z "$(git status --porcelain)" ]; then 
+            echo "Spotless PASS"
+          else 
+            echo "Spotless FAIL; run `mvn spotless:apply` locally" >&2
+          fi
